# Generated by Django 3.1.2 on 2020-10-28 10:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clinic', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='medicalhistory',
            name='id',
        ),
        migrations.AlterField(
            model_name='medicalhistory',
            name='illness',
            field=models.CharField(max_length=200, primary_key=True, serialize=False),
        ),
    ]
