# Generated by Django 3.1.2 on 2020-10-28 11:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clinic', '0002_auto_20201028_1647'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patient',
            name='contact',
            field=models.IntegerField(unique=True),
        ),
    ]
